version: '3'
services:
  blockchain:
    container_name: blockchain
    restart: always
    build: .
    image: blockchain
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    networks:
      - blockchain

networks:
  blockchain:
    external: true