version: '3'
services:
  data_lake:
    container_name: blockchain
    restart: always
    build: .
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    networks:
      - blockchain

networks:
  serums:
    external: true